name: Patch Permissions xmls

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run patch script
        run: python scripts/modify_xmls.py

      - name: Upload patched zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: patched_permissions.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
