name: Patch Permission XMLs and Release

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run patch script
        run: |
          python scripts/modify_xmls.py
          ls -la

      - name: Create Git Tag (patch-1)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag patch-1
          git push origin patch-1

      - name: Upload patched zip to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: patch-1
          files: patched_permission.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
